runtime-rs: Fix duplicated definitions of tests
```
error[E0428]: the name `tests` is defined multiple times
    --> src/runtime-rs/crates/runtimes/src/manager.rs:1010:1
     |
  93 | mod tests {
     | --------- previous definition of the module `tests` here
...
1010 | mod tests {
     | ^^^^^^^^^ `tests` redefined here
     |
     = note: `tests` must be defined only once in the type namespace of
this module

   Compiling runtime-rs v0.1.0
(/home/runner/work/kata-containers/kata-containers/src/runtime-rs)
```

Signed-off-by: Alex Lyn <alex.lyn@antgroup.com>