ci: Make Azure region configurable
The AKS error below has been reported for a few CI runs lately:

  ERROR: (Throttled) The PutManagedClusterHandler.PUT request limit has
  been exceeded for SubID=***, please retry again in 8 seconds. For more
  information, please visit aka.ms/aks/throttling

  https://github.com/kata-containers/kata-containers/actions/runs/12891699930/job/35946395320?pr=10770#step:8:31

This error might only be impacting certain regions. So to attempt to
swiftly address this and similar issues in the future, I created the
AZ_REGION repo variable and set it to eastus2 instead of eastus for now.

Signed-off-by: Aurélien Bombo <abombo@microsoft.com>