deploy: Allow container to restart gracefully
If the container has had to restart, lack of overwrite here causes a benign error message to appear since the nodes already have `katacontainers.io/kata-runtime=true` label. Having a overwrite here means that we don't get the following error message:

    error: 'katacontainers.io/kata-runtime' already has a value (true), and --overwrite is false

Signed-off-by: Bharat Kunwar <b.kunwar@gmail.com>