k8s: mute message when runtimeclass is not configured
When runtimeclass is not configured on a test environment,
it is normal that we get this message:
```
error: the server doesn't have a resource type "runtimeclass"
```

This message is not the cause of a test failure, since we
use old trusted and untrusted tags when runtimeclass is not
configured.
To avoid confusion, lets send the message to /dev/null.

Fixes: #1196.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>