agent - remove intialization of kmem limits
We have seen logs in production where containers failed to start with the following error:
```
Error: failed to create containerd task: failed to create shim task: unable to write to a control group file memory.kmem.limit_in_bytes, value 1 caused by: Os { code: 16, kind: ResourceBusy, message: "Resource busy" }
```

After considering implementing different "strategy" based on managers, I took the path
of removing the "double write" altogether:

- memory accounting is already was already enabled by default in (at least) 5.4
- the `memory.kmem.limit_in_bytes` is deprecated in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0158115f702b0ba208ab0b5adf44cae99b3ebcc7
  and removed in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=58056f77502f3567b760c9a8fc8d2e9081515b2d.

Signed-off-by: François Serman <fserman@apple.com>