kata-ctl: Ensure GENERATED_CODE is a dep of `make test`
Otherwise `make test` will simply fail with:
```
error[E0583]: file not found for module `version`
```

Fixes: #7974 -- part 0

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
(cherry picked from commit 46daddc5005c95718e26a2841515ee40823031ce)