runtime-rs: Ensure static-checks-build is a dep of `make test`
Otherwise `make test` will simply fail with:
```
error[E0583]: file not found for module `config`
```

Fixes: #7974 -- part 0

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
(cherry picked from commit 08f2e5ae0bbdc2e6c08b2ec29f29404207b2c2fb)