checks: fix error when making test
Fix error in PR #7837: https://github.com/kata-containers/kata-containers/actions/runs/8521057440/job/23338469953?pr=7837
```
error: failed to run custom build command for `devicemapper-sys v0.3.0`
Caused by:
  process didn't exit successfully: `/home/runner/work/kata-containers/kata-containers/src/agent/target/
  debug/build/devicemapper-sys-7ea9487de3a4b992/build-script-build` (exit status: 101)
  --- stderr
  dm.h:2:10: fatal error: 'libdevmapper.h' file not found
  thread 'main' panicked at 'Could not generate dm.h bindings: ClangDiagnostic("dm.h:2:10: fatal error: 'libdevmapper.h' file not found\n")',
   /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/devicemapper-sys-0.3.0/build.rs:24:10
```

Signed-off-by: ChengyuZhu6 <chengyu.zhu@intel.com>