tests: Reduce AKS cluster name length
For the last 30+ days the cloud-hypervisor and
qemu-runtime-rs hypervisor AKS tests have failed with:
```
Error: The action 'Create AKS cluster' has timed out after 10 minutes.
```

Although the error is not at all helpful I spotted that the cluster names
`kataCI-k8s-nightly-<12 char sha>-qemu-runtime-rs-ubuntu-amd64-s-o`
and `kataCI-k8s-nightly-<12 char sha>-cloud-hypervisor-ubuntu-amd64-s-o`
are 64 and 65 characters and the limit is 63 chars, so only
take the first 8 chars of the sha, not the first 12. This is somewhat temporary,
so it would still be good to understand if we can get a proper output from the
`az` cli.

Signed-off-by: stevenhorsman <steven@uk.ibm.com>