workflow: Revert "workflow: trigger test-kata-deploy with pull_request"
This reverts commit 7676cde0c5c4e5a99bca626770e534cab48c1db7.
It turns out that when triggerred from a PR, the docker login command is
failing with
```
Error: Cannot perform an interactive login from a non TTY device
```

Signed-off-by: Peng Tao <bergwolf@hyper.sh>