error: Fix error formatting and improve message
Failing to dial the mux address would result in an incorrectly
formatted error message due to calling `logrus.Fail()` rather than
`logrus.Failf()`.

Also improved wording and quoted the address string.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>