agent: Ensure GENERATED_CODE is a dep of `make test`
Otherwise `make test` will fail with:
```
error[E0583]: file not found for module `version`
```

Fixes: #7974 -- part 0

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
(cherry picked from commit ec826f328f88a1ff665c37381ada069eec337e65)